### Importar las librerías

In [21]:
import pandas as pd
import numpy as np

In [22]:
# Cargar los archivos CSV con las columnas que nos interesan

df_team = pd.read_csv('csv/team.csv', usecols=['id', 'full_name','abbreviation','city', 'state'])
df_team_details = pd.read_csv('csv/team_details.csv', usecols=['team_id','owner', 'generalmanager','headcoach', 'arena', 'arenacapacity'])
df_team_history = pd.read_csv('csv/team_history.csv', usecols=['team_id', 'year_founded', 'year_active_till'])
df_draft_combine_stats = pd.read_csv('csv/draft_combine_stats.csv', usecols=['player_id','weight','wingspan','standing_reach','body_fat_pct','standing_vertical_leap','max_vertical_leap','lane_agility_time','modified_lane_agility_time','three_quarter_sprint','bench_press'])
df_draft_history = pd.read_csv('csv/draft_history.csv', usecols=['person_id','season','player_name','round_number','round_pick','overall_pick','team_id','organization','organization_type'])
df_common_player_info = pd.read_csv('csv/common_player_info.csv', usecols=['person_id', 'first_name', 'last_name', 'height', 'weight', 'season_exp', 'jersey', 'position', 'team_id', 'team_city', 'team_name'])
df_inactive_players = pd.read_csv('csv/inactive_players.csv', usecols=['game_id', 'player_id', 'first_name', 'last_name', 'jersey_num', 'team_id', 'team_city', 'team_name'])
df_player = pd.read_csv('csv/player.csv', usecols=['id', 'full_name', 'first_name', 'last_name', 'is_active'])
df_game = pd.read_csv('csv/game.csv', usecols=['season_id', 'team_id_home', 'game_id', 'game_date', 'wl_home', 'pts_home', 'team_id_away', 'wl_away','pts_away'])  
df_game_info = pd.read_csv('csv/game_info.csv', usecols=['game_id', 'attendance', 'game_time'])  
df_game_summary = pd.read_csv('csv/game_summary.csv', usecols=['game_id', 'season'])  
df_line_score = pd.read_csv('csv/line_score.csv', usecols=['game_id', 'team_city_name_home', 'team_nickname_home' , 'team_city_name_away', 'team_nickname_away'])
df_other_stats = pd.read_csv('csv/other_stats.csv', usecols=['game_id', 'team_id_home', 'team_city_home', 'pts_paint_home', 'times_tied', 'total_turnovers_home', 'team_id_away', 'team_city_away', 'pts_paint_away', 'total_turnovers_away'])
df_nba_salaries = pd.read_csv('csv/nba_salaries.csv', usecols=['Player Name', 'Salary', 'Position', 'Age', 'Team', 'PTS'])

### DataFrame Teams

In [23]:
# Se renombra la columna 'id' por 'team_id'
df_team = df_team.rename(columns={'id': 'team_id'})

# Se fusionan los DataFrames 'df_team', 'df_team_detail' y 'df_team_history' con base en la columna 'team_id'
df_teams = df_team.merge(df_team_details, on='team_id').merge(df_team_history, on='team_id')

# Llenamos los nulos de las columnas 'headcoach' y 'arenacapacity' y la pasamos a tipo int 
df_teams['arenacapacity'] = df_teams['arenacapacity'].fillna(0)
df_teams['headcoach'] = df_teams['headcoach'].fillna('No Data')
df_teams['arenacapacity'] = df_teams['arenacapacity'].astype(int)

# Eliminar filas duplicadas basadas en la columna 'team_id'
df_teams = df_teams.drop_duplicates(subset='team_id')

# # Se guarda el archivo en la carpeta DF para ser cargado a la DB
df_teams.to_csv('DF/df_teams.csv', index=False)

df_teams

,team_id,full_name,abbreviation,city,state,arena,arenacapacity,owner,generalmanager,headcoach,year_founded,year_active_till
0,1610612737,Atlanta Hawks,ATL,Atlanta,Atlanta,State Farm Arena,18729,Tony Ressler,Travis Schlenk,Quin Snyder,1968,2019
4,1610612741,Chicago Bulls,CHI,Chicago,Illinois,United Center,21711,Michael Reinsdorf,Arturas Karnisovas,Billy Donovan,1966,2019
5,1610612742,Dallas Mavericks,DAL,Dallas,Texas,American Airlines Center,19200,Mark Cuban,Nico Harrison,Jason Kidd,1980,2019
6,1610612743,Denver Nuggets,DEN,Denver,Colorado,Ball Arena,0,Stan Kroenke,Calvin Booth,Michael Malone,1976,2019
7,1610612744,Golden State Warriors,GSW,Golden State,California,Chase Center,0,Joe Lacob,Bob Myers,Steve Kerr,1971,2019
10,1610612745,Houston Rockets,HOU,Houston,Texas,Toyota Center,18104,Tilman Fertitta,Rafael Stone,Ime Udoka,1971,2019
12,1610612746,Los Angeles Clippers,LAC,Los Angeles,California,Crypto.com Arena,19060,Steve Ballmer,Michael Winger,Tyronn Lue,1984,2019
15,1610612747,Los Angeles Lakers,LAL,Los Angeles,California,Crypto.com Arena,19060,Jeanie Buss,Rob Pelinka,Darvin Ham,1960,2019
17,1610612748,Miami Heat,MIA,Miami,Florida,Kaseya Center,19600,Micky Arison,Pat Riley,Erik Spoelstra,1988,2019
18,1610612749,Milwaukee Bucks,MIL,Milwaukee,Wisconsin,Fiserv Forum,17500,Wesley Edens & Marc Lasry,Jon Horst,Adrian Griffin,1968,2019
19,1610612750,Minnesota Timberwolves,MIN,Minnesota,Minnesota,Target Center,19356,Glen Taylor,Tim Connelly,Chris Finch,1989,2019
20,1610612751,Brooklyn Nets,BKN,Brooklyn,New York,Barclays Center,0,Joe Tsai,Sean Marks,Jacque Vaughn,2012,2019
23,1610612754,Indiana Pacers,IND,Indiana,Indiana,Gainbridge Fieldhouse,18345,Herb Simon,Kevin Pritchard,Rick Carlisle,1976,2019
24,1610612755,Philadelphia 76ers,PHI,Philadelphia,Pennsylvania,Wells Fargo Center,0,Joshua Harris & David Blitzer,Elton Brand,Nick Nurse,1963,2019
26,1610612756,Phoenix Suns,PHX,Phoenix,Arizona,Footprint Center,0,Mat Ishbia,James Jones,Frank Vogel,1968,2019
27,1610612757,Portland Trail Blazers,POR,Portland,Oregon,Moda Center,19980,Jody Allen,Joe Cronin,Chauncey Billups,1970,2019
28,1610612758,Sacramento Kings,SAC,Sacramento,California,Golden 1 Center,17500,Vivek Ranadive,Monte McNair,Mike Brown,1985,2019
33,1610612759,San Antonio Spurs,SAS,San Antonio,Texas,AT&T Center,18694,Peter Holt,Brian Wright,Gregg Popovich,1976,2019
34,1610612760,Oklahoma City Thunder,OKC,Oklahoma City,Oklahoma,Paycom Center,0,Clay Bennett,Sam Presti,Mark Daigneault,2008,2019
36,1610612761,Toronto Raptors,TOR,Toronto,Ontario,Scotiabank Arena,0,Lawrence Tanenbaum,Masai Ujiri,No Data,1995,2019
37,1610612762,Utah Jazz,UTA,Utah,Utah,Delta Center,0,Ryan Smith,Justin Zanik,Will Hardy,1979,2019
39,1610612763,Memphis Grizzlies,MEM,Memphis,Tennessee,FedExForum,18119,Robert Pera,Zach Kleiman,Taylor Jenkins,2001,2019
41,1610612764,Washington Wizards,WAS,Washington,District of Columbia,Capital One Arena,20647,Ted Leonsis,Tommy Sheppard,Wes Unseld,1997,2019
47,1610612765,Detroit Pistons,DET,Detroit,Michigan,Little Caesars Arena,0,Tom Gores,Ed Stefanski,Monty Williams,1957,2019
49,1610612766,Charlotte Hornets,CHA,Charlotte,North Carolina,Spectrum Center,19026,Michael Jordan,Mitch Kupchak,Steve Clifford,2014,2019

### DataFrame Drafts

In [24]:
# Se renombra la columna 'person_id' por 'player_id'
df_draft_history = df_draft_history.rename(columns={'person_id': 'player_id'})

# Se fusionan los DataFrames 'df_draft_combine_stats' y 'df_draft_history' con base en la columna 'player_id'
df_drafts = df_draft_combine_stats.merge(df_draft_history, on='player_id')

# Llenamos los nulos de las columnas 'weight', 'wingspan', 'standing_reach', 'body_fat_pct', 'standing_vertical_leap', 'max_vertical_leap',
# 'lane_agility_time', 'modified_lane_agility_time', 'three_quarter_sprint', 'bench_press' y pasamos esta última a tipo int 
df_drafts['weight'] = df_drafts['weight'].fillna(0)
df_drafts['wingspan'] = df_drafts['wingspan'].fillna(0)
df_drafts['standing_reach'] = df_drafts['standing_reach'].fillna(0)
df_drafts['body_fat_pct'] = df_drafts['body_fat_pct'].fillna(0)
df_drafts['standing_vertical_leap'] = df_drafts['standing_vertical_leap'].fillna(0)
df_drafts['max_vertical_leap'] = df_drafts['max_vertical_leap'].fillna(0)
df_drafts['lane_agility_time'] = df_drafts['lane_agility_time'].fillna(0)
df_drafts['modified_lane_agility_time'] = df_drafts['modified_lane_agility_time'].fillna(0)
df_drafts['three_quarter_sprint'] = df_drafts['three_quarter_sprint'].fillna(0)
df_drafts['bench_press'] = df_drafts['bench_press'].fillna(0)
df_drafts['bench_press'] = df_drafts['bench_press'].astype(int)

# Eliminar filas duplicadas basadas en la columna 'player_id'
df_drafts = df_drafts.drop_duplicates(subset='player_id')

# Se guarda el archivo en la carpeta DF para ser cargado a la DB
df_drafts.to_csv('DF/df_drafts.csv', index=False)

df_drafts

,player_id,weight,wingspan,standing_reach,body_fat_pct,standing_vertical_leap,max_vertical_leap,lane_agility_time,modified_lane_agility_time,three_quarter_sprint,bench_press,player_name,season,round_number,round_pick,overall_pick,team_id,organization,organization_type
0,2240,199.0,81.50,99.5,5.3,31.5,36.0,0.00,0.00,3.25,12,Gilbert Arenas,2001,2,2,30,1610612744,Arizona,College/University
1,2220,188.0,81.50,99.5,9.3,30.0,37.0,10.91,0.00,3.20,6,Brandon Armstrong,2001,1,23,23,1610612745,Pepperdine,College/University
2,2203,229.0,82.50,105.0,9.3,29.5,33.0,10.95,0.00,3.30,12,Shane Battier,2001,1,6,6,1610612763,Duke,College/University
3,2257,245.0,88.00,111.0,6.0,26.5,31.0,11.84,0.00,3.33,6,Ruben Boumtje-Boumtje,2001,2,21,49,1610612757,Georgetown,College/University
4,2214,227.0,85.50,107.0,9.3,27.0,30.0,11.11,0.00,3.35,13,Michael Bradley,2001,1,17,17,1610612761,Villanova,College/University
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,1641775,204.0,85.75,107.0,0.0,33.0,36.0,10.83,0.00,3.30,0,Jordan Walsh,2023,2,8,38,1610612758,Arkansas,College/University
715,1641705,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0,Victor Wembanyama,2023,1,1,1,1610612759,Metropolitans 92 (France),Other Team/Club
716,1641727,217.2,82.25,103.5,0.0,0.0,0.0,0.00,0.00,0.00,0,Dariq Whitehead,2023,1,22,22,1610612751,Duke,College/University
717,1641715,235.0,80.50,103.5,0.0,31.5,40.5,10.82,3.33,3.20,0,Cam Whitmore,2023,1,20,20,1610612745,Villanova,College/University
719,1631209,178.4,78.75,97.5,0.0,32.5,37.0,10.93,0.00,3.22,0,Isaiah Wong,2023,2,25,55,1610612754,Miami (FL),College/University

### DataFrame Players

In [25]:
# Se renombran las columnas 'id' y 'person_id' por 'player_id'
df_common_player_info = df_common_player_info.rename(columns={'person_id': 'player_id'})
df_player = df_player.rename(columns={'id': 'player_id'})

# Se fusionan los DataFrames 'df_common_player_info' y 'df_player' con base en la columna 'player_id'
df_players = df_common_player_info.merge(df_player, on='player_id')

# Llenamos los nulos de las columnas 'height', 'weight', 'jersey', 'position', 'team_name', 'team_city' y pasamos 'weight' y 'season_exp' a tipo int 
df_players['height'] = df_players['height'].fillna(0)
df_players['weight'] = df_players['weight'].fillna(0)
df_players['jersey'] = df_players['jersey'].fillna(0)
df_players['position'] = df_players['position'].fillna('No Data')
df_players['team_name'] = df_players['team_name'].fillna('No Data')
df_players['team_city'] = df_players['team_city'].fillna('No Data')
df_players['weight'] = df_players['weight'].astype(int)
df_players['season_exp'] = df_players['season_exp'].astype(int)

# Se eliminan las columnas 'first_name_x', 'last_name_x', 'first_name_y' y 'last_name_y'
df_players = df_players.drop(columns=['first_name_x', 'last_name_x', 'first_name_y', 'last_name_y'])

# Se eliminan las filas duplicadas basadas en la columna 'player_id'
df_players = df_players.drop_duplicates(subset='player_id')

# Se guarda el archivo en la carpeta DF para ser cargado a la DB
df_players.to_csv('DF/df_players.csv', index=False)

df_players

,player_id,height,weight,season_exp,jersey,position,team_id,team_name,team_city,full_name,is_active
0,76001,6-10,240,5,30,Forward,1610612757,Trail Blazers,Portland,Alaa Abdelnaby,0
1,76003,7-2,225,20,33,Center,1610612747,Lakers,Los Angeles,Kareem Abdul-Jabbar,0
2,1505,6-6,235,7,9,Forward-Guard,1610612758,Kings,Sacramento,Tariq Abdul-Wahad,0
3,949,6-9,245,13,3,Forward,1610612763,Grizzlies,Vancouver,Shareef Abdur-Rahim,0
4,76005,6-7,220,5,5,Forward,1610612744,Warriors,Golden State,Tom Abernethy,0
...,...,...,...,...,...,...,...,...,...,...,...
4166,1627835,6-8,226,2,16,Forward,1610612741,Bulls,Chicago,Paul Zipser,0
4167,1627790,6-10,266,4,41,Center,1610612739,Cavaliers,Cleveland,Ante Zizic,0
4168,78647,7-1,240,1,34,Center,1610612765,Pistons,Detroit,Jim Zoet,0
4169,1627826,7-0,240,7,40,Center,1610612746,Clippers,LA,Ivica Zubac,1
4170,78650,6-3,195,1,0,Guard,1610610036,Capitols,Washington,Matt Zunic,0

### DataFrame Games

In [26]:
# Se fusionan los DataFrames 'df_game', 'df_game_info', 'df_game_summary' y 'df_line_score' con base en la columna 'game_id'
df_games = df_game.merge(df_game_info, on='game_id').merge(df_game_summary, on='game_id').merge(df_line_score, on='game_id')

# Llenamos los nulos de la columna 'attendance' y pasamos a tipo int las columnas 'pts_home', 'pts_away' y 'attendance' 
df_games['attendance'] = df_games['attendance'].fillna(0)
df_games['pts_home'] = df_games['pts_home'].astype(int)
df_games['pts_away'] = df_games['pts_away'].astype(int)
df_games['attendance'] = df_games['attendance'].astype(int)

# Se filtra la columna 'season'>2014 para dejar las temporadas desde el 2015
df_games = df_games[df_games['season']>2014]

# Y se eliminan filas duplicadas basadas en la columna 'game_id'
df_games = df_games.drop_duplicates(subset='game_id')

# Se guarda el archivo en la carpeta DF para ser cargado a la DB
df_games.to_csv('DF/df_games.csv', index=False)

df_games

,season_id,team_id_home,game_id,game_date,wl_home,pts_home,team_id_away,wl_away,pts_away,attendance,game_time,season,team_city_name_home,team_nickname_home,team_city_name_away,team_nickname_away
48867,22015,1610612737,21500001,2015-10-27 00:00:00,L,94,1610612765,W,106,19187,2:11,2015,Detroit,Pistons,Atlanta,Hawks
48868,22015,1610612744,21500003,2015-10-27 00:00:00,W,111,1610612740,L,95,19596,2:25,2015,Golden State,Warriors,New Orleans,Pelicans
48869,22015,1610612741,21500002,2015-10-27 00:00:00,W,97,1610612739,L,95,21957,2:22,2015,Cleveland,Cavaliers,Chicago,Bulls
48870,22015,1610612738,21500005,2015-10-28 00:00:00,W,112,1610612755,L,95,18624,2:14,2015,Philadelphia,76ers,Boston,Celtics
48871,22015,1610612748,21500008,2015-10-28 00:00:00,W,104,1610612766,L,94,19724,2:19,2015,Miami,Heat,Charlotte,Hornets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58659,42022,1610612743,42200402,2023-06-04 00:00:00,L,108,1610612748,W,111,19537,2:25,2022,Denver,Nuggets,Miami,Heat
58660,42022,1610612748,42200403,2023-06-07 00:00:00,L,94,1610612743,W,109,20019,2:24,2022,Miami,Heat,Denver,Nuggets
58661,42022,1610612748,42200404,2023-06-09 00:00:00,L,95,1610612743,W,108,20184,2:29,2022,Miami,Heat,Denver,Nuggets
58662,42022,1610612743,42200405,2023-06-12 00:00:00,W,94,1610612748,L,89,19537,2:22,2022,Denver,Nuggets,Miami,Heat
58663,32022,1610616834,32200001,2023-02-19 00:00:00,L,175,1610616833,W,184,17886,0:00,2022,Team,LeBron,Team,Giannis

### DataFrame Other Stats

In [27]:
# Llenamos los nulos de las columnas 'total_turnovers_home' y 'total_turnovers_away' y pasamos a tipo int las mismas columnas  
df_other_stats['total_turnovers_home'] = df_other_stats['total_turnovers_home'].fillna(0)
df_other_stats['total_turnovers_away'] = df_other_stats['total_turnovers_away'].fillna(0)
df_other_stats['total_turnovers_home'] = df_other_stats['total_turnovers_home'].astype(int)
df_other_stats['total_turnovers_away'] = df_other_stats['total_turnovers_away'].astype(int)

# Y se eliminan filas duplicadas basadas en la columna 'game_id'
df_other_stats = df_other_stats.drop_duplicates(subset='game_id')

# Se guarda el archivo en la carpeta DF para ser cargado a la DB
df_other_stats.to_csv('DF/df_other_stats.csv', index=False)

df_other_stats

,game_id,team_id_home,team_city_home,pts_paint_home,times_tied,total_turnovers_home,team_id_away,team_city_away,pts_paint_away,total_turnovers_away
0,29600012,1610612756,Phoenix,44,1,12,1610612747,Los Angeles,42,23
1,29600005,1610612737,Atlanta,32,0,24,1610612748,Miami,32,19
2,29600002,1610612739,Cleveland,36,1,15,1610612751,New Jersey,26,22
3,29600007,1610612754,Indiana,34,4,18,1610612765,Detroit,30,19
4,29600013,1610612746,Los Angeles,40,4,20,1610612744,Golden State,30,20
...,...,...,...,...,...,...,...,...,...,...
28265,42200401,1610612748,Miami,38,2,8,1610612743,Denver,46,10
28266,42200402,1610612743,Denver,50,3,14,1610612748,Miami,34,11
28267,42200403,1610612748,Miami,34,7,4,1610612743,Denver,60,14
28268,42200404,1610612743,Denver,48,6,8,1610612748,Miami,46,15
28269,32200001,1610616834,Team,118,14,10,1610616833,Team,88,12

### DataFrame NBA Salaries

In [28]:
# Se renombra la columna 'Player Name' por 'full_name'
df_nba_salaries = df_nba_salaries.rename(columns={'Player Name': 'full_name'})

# Se fusionan los DataFrames 'df_nba_salaries' y 'df_player' con base en la columna 'full_name'
df_nba_salaries = df_nba_salaries.merge(df_player, on='full_name')

# Se eliminan las columnas 'first_name' y 'last_name'
df_nba_salaries = df_nba_salaries.drop(columns=['first_name', 'last_name'])

# Se renombra la columna 'id' por 'player_id'
df_nba_salaries = df_nba_salaries.rename(columns={'id': 'player_id'})

# Se guarda el archivo en la carpeta DF para ser cargado a la DB
df_nba_salaries.to_csv('DF/df_nba_salaries.csv', index=False)

df_nba_salaries

,full_name,Salary,Position,Age,Team,PTS,player_id,is_active
0,Stephen Curry,48070014,PG,34,GSW,29.4,201939,1
1,John Wall,47345760,PG,32,LAC,11.4,202322,1
2,Russell Westbrook,47080179,PG,34,LAL/LAC,15.9,201566,1
3,LeBron James,44474988,PF,38,LAL,28.9,2544,1
4,Kevin Durant,44119845,PF,34,BRK/PHO,29.1,201142,1
...,...,...,...,...,...,...,...,...
458,Jeenathan Williams,52644,SG,23,POR,10.6,1631466,1
459,Jay Scrubb,49719,SG,22,ORL,6.5,1630206,1
460,Kobi Simmons,32795,SG,25,CHO,1.0,1628424,0
461,Gabe York,32171,SG,29,IND,8.0,1628221,0
462,RaiQuan Gray,5849,PF,23,BRK,16.0,1630564,1

### Manejo de ID faltantes

In [29]:
# Función que toma los DataFrames fuente y destino, la columna de ID y un diccionario 
# con valores por defecto para crear y agregar las entradas faltantes.

def add_missing_entries(source_df, target_df, id_column, default_values):
    missing_ids = source_df[~source_df[id_column].isin(target_df[id_column])][id_column].unique()
    missing_entries = pd.DataFrame(missing_ids, columns=[id_column])
    for column, value in default_values.items():
        missing_entries[column] = value
    return pd.concat([target_df, missing_entries], ignore_index=True)

# Valores por defecto para player_id, team_id y game_id
default_player_values = {
    'height': 'Unknown', 'weight': 0, 'season_exp': 0, 'jersey': 'Unknown',
    'position': 'Unknown', 'team_id': 0, 'team_name': 'Unknown', 'team_city': 'Unknown',
    'full_name': 'Unknown', 'is_active': 0
}

default_team_values = {
    'full_name': 'Unknown', 'abbreviation': 'UNK', 'city': 'Unknown', 'state': 'Unknown',
    'arena': 'Unknown', 'arenacapacity': 0, 'owner': 'Unknown',
    'generalmanager': 'Unknown', 'headcoach': 'Unknown', 'year_founded': 0,
    'year_active_till': 0
}

default_game_values = {
    'season_id': 0, 'team_id_home': 0, 'game_date': 'Unknown', 'wl_home': 'Unknown',
    'pts_home': 0, 'team_id_away': 0, 'wl_away': 'Unknown', 'pts_away': 0,
    'attendance': 0, 'game_time': 'Unknown', 'season': 0, 'team_city_name_home': 'Unknown',
    'team_nickname_home': 'Unknown', 'team_city_name_away': 'Unknown', 'team_nickname_away': 'Unknown'
}

# Actualizar df_players con jugadores faltantes
df_players = add_missing_entries(df_drafts, df_players, 'player_id', default_player_values)
df_players = add_missing_entries(df_nba_salaries, df_players, 'player_id', default_player_values)

# Actualizar df_teams con equipos faltantes
df_teams = add_missing_entries(df_players, df_teams, 'team_id', default_team_values)

# Identificar team_id_home y team_id_away faltantes en df_games
missing_team_id_home = df_games[~df_games['team_id_home'].isin(df_teams['team_id'])]['team_id_home'].unique()
missing_team_id_away = df_games[~df_games['team_id_away'].isin(df_teams['team_id'])]['team_id_away'].unique()

# Convertir los IDs faltantes a DataFrames
missing_team_id_home = pd.DataFrame(missing_team_id_home, columns=['team_id'])
missing_team_id_away = pd.DataFrame(missing_team_id_away, columns=['team_id'])

missing_team_ids = pd.concat([missing_team_id_home, missing_team_id_away]).drop_duplicates()
df_teams = add_missing_entries(missing_team_ids, df_teams, 'team_id', default_team_values)

# Actualizar df_games con juegos faltantes
df_games = add_missing_entries(df_other_stats, df_games, 'game_id', default_game_values)

# Guardar los DataFrames actualizados
df_players.to_csv('DF/df_players.csv', index=False)
df_games.to_csv('DF/df_games.csv', index=False)
df_teams.to_csv('DF/df_teams.csv', index=False)